import { useMemo, useState } from 'react'
import { BookOpenCheck, Braces, Copy, Eye, Filter, FolderOpen, MoreHorizontal, Plus, Search, Tag } from 'lucide-react'
import { questionBank } from '../../data'
import { useApp } from '../../context/AppContext'
import { Button, Modal, StatusBadge } from '../../components/UI'
import type { CodingQuestion, QuestionDifficulty } from '../../types'

export function QuestionBankPage() {
  const { notify } = useApp()
  const [query, setQuery] = useState('')
  const [difficulty, setDifficulty] = useState<'All' | QuestionDifficulty>('All')
  const [selected, setSelected] = useState<CodingQuestion | null>(null)
  const [createOpen, setCreateOpen] = useState(false)
  const filtered = useMemo(() => questionBank.filter((question) => (difficulty === 'All' || question.difficulty === difficulty) && (question.title.toLowerCase().includes(query.toLowerCase()) || question.category.toLowerCase().includes(query.toLowerCase()))), [difficulty, query])

  return <div className="content-stack"><section className="bank-summary"><div><span><BookOpenCheck /></span><div><strong>{questionBank.length}</strong><small>curated questions</small></div></div><i /><div><span><Braces /></span><div><strong>4</strong><small>supported languages</small></div></div><i /><div><span><FolderOpen /></span><div><strong>9</strong><small>skill categories</small></div></div><Button icon={<Plus size={17} />} onClick={() => setCreateOpen(true)}>Create question</Button></section><section className="panel question-bank-panel"><div className="table-toolbar"><div className="toolbar-actions"><label className="search-field search-field--wide"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search question bank…" /></label><select value={difficulty} onChange={(event) => setDifficulty(event.target.value as typeof difficulty)}><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select><button className="filter-button"><Filter size={16} />More filters</button></div><span>{filtered.length} questions</span></div><div className="question-bank-grid">{filtered.map((question) => <article key={question.id}><header><span className="question-type"><Braces size={16} />CODING</span><button className="icon-button"><MoreHorizontal size={17} /></button></header><div><StatusBadge tone={question.difficulty === 'Easy' ? 'green' : question.difficulty === 'Medium' ? 'amber' : 'red'} dot={false}>{question.difficulty}</StatusBadge><span>{question.category}</span></div><h3>{question.title}</h3><p>{question.summary}</p><div className="question-tags">{question.tags.slice(0, 3).map((tag) => <span key={tag}><Tag size={11} />{tag}</span>)}</div><footer><div><strong>{question.points} pts</strong><span>{question.testCases.length} tests · {question.estimatedMinutes} min</span></div><div><button className="icon-button" onClick={() => { notify('Question duplicated into your library.'); }}><Copy size={15} /></button><button className="icon-button" onClick={() => setSelected(question)}><Eye size={15} /></button></div></footer></article>)}</div>{!filtered.length && <div className="table-empty"><Search size={24} /><h3>No questions found</h3><p>Try a different keyword or difficulty.</p></div>}</section>
    <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={selected?.title || ''} eyebrow={`${selected?.category || ''} challenge`} width="lg" footer={<><Button variant="ghost" onClick={() => setSelected(null)}>Close</Button><Button onClick={() => { notify('Question added to a new draft assessment.'); setSelected(null) }}>Use in assessment</Button></>}><div className="question-preview-modal"><div><StatusBadge tone={selected?.difficulty === 'Easy' ? 'green' : selected?.difficulty === 'Medium' ? 'amber' : 'red'}>{selected?.difficulty}</StatusBadge><span>{selected?.points} points</span><span>{selected?.estimatedMinutes} minutes</span></div><p>{selected?.description}</p><h4>Example</h4><div className="example-box"><span><b>Input</b><code>{selected?.examples[0]?.input}</code></span><span><b>Output</b><code>{selected?.examples[0]?.output}</code></span></div><h4>Constraints</h4><ul>{selected?.constraints.map((item) => <li key={item}>{item}</li>)}</ul></div></Modal>
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Start a new question" eyebrow="Question bank" width="sm" footer={<><Button variant="ghost" onClick={() => setCreateOpen(false)}>Cancel</Button><Button onClick={() => { setCreateOpen(false); notify('Question draft created. Open an exam to finish adding tests.') }}>Create draft</Button></>}><div className="simple-create"><label className="form-field"><span>Question title</span><input placeholder="Give this challenge a name" /></label><label className="form-field"><span>Difficulty</span><select><option>Easy</option><option>Medium</option><option>Hard</option></select></label><label className="form-field"><span>Category</span><input placeholder="Arrays, Strings, Graphs…" /></label></div></Modal>
  </div>
}
